/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.sample.testing;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

@Tag("slow")
class LibraryTestSlow {

    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");

        System.out.println("Class:         " + Library.class.getSimpleName());
        System.out.println("Module:        " + Library.class.getModule().getName());
        System.out.println("Resource:      " + Library.class.getResource("/lib.properties"));

        System.out.println("Test Class:    " + LibraryTestSlow.class.getSimpleName());
        System.out.println("Test Module:   " + LibraryTestSlow.class.getModule().getName());
        System.out.println("Test Resource: " + LibraryTestSlow.class.getResource("/libTest.properties"));
    }
}
