/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.sample.testing;

import org.junit.Test;
import org.junit.experimental.categories.Category;

import static org.junit.Assert.assertTrue;

@Category(SlowTests.class)
public class LibraryTestSlow {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        System.out.println("Class:         " + Library.class.getSimpleName());
        System.out.println("Module:        " + Library.class.getModule().getName());
        System.out.println("Resource:      " + Library.class.getResource("/lib.properties"));

        System.out.println("Test Class:    " + LibraryTestSlow.class.getSimpleName());
        System.out.println("Test Module:   " + LibraryTestSlow.class.getModule().getName());
        System.out.println("Test Resource: " + LibraryTestSlow.class.getResource("/libTest.properties"));
    }
}
