/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.sample.testing;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        System.out.println("Class:         " + Library.class.getSimpleName());
        System.out.println("Module:        " + Library.class.getModule().getName());
        System.out.println("Resource:      " + Library.class.getResource("/lib.properties"));

        System.out.println("Test Class:    " + LibraryTest.class.getSimpleName());
        System.out.println("Test Module:   " + LibraryTest.class.getModule().getName());
        System.out.println("Test Resource: " + LibraryTest.class.getResource("/libTest.properties"));
    }
}
